"""Validated, shared domain constants for emergency resource allocation."""

TOTAL_DEMAND = 400
TEAM_CAPACITY = 20
VEHICLE_CAPACITY = 15
MIN_RESPONSE_TIME = 8
BASE_RESPONSE_TIME = 55
COST_PER_TEAM = 30000
COST_PER_VEHICLE = 15000
FIXED_OPS_COST = 50000
MIN_COVERAGE_PCT = 60
